
[build] 
  publish = "public" 
  functions = "netlify/functions" 

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs] 
    include = [ "views/**", "public/**" ]

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "cors", "dotenv", "path", "@fortawesome/fontawesome-free", "serverless-http", "ejs"]
  node_bundler = "esbuild"
  included_files = [ "views/**", "public/**" ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200